### PR TITLE
Added the getObject(GetObjectRequest, File) function.

### PR DESCRIPTION
**Pull request by marcinx27**
Added the getObject(GetObjectRequest, File) function.  Now, all of the getObject functions from the AWS S3 SDK are included.

### CODE REVIEW

**Comment by dwhjames** [comment]
:+1:

Btw, you can avoid the `{ case …` with
http://www.scala-lang.org/api/2.11.5/index.html#scala.Function2@tupled:((T1,T2))=>R

**Comment by marcinx27** [comment]
@dwhjames cool, thanks.  I was getting a bunch of red lines under that for a bit, so I figured I'd be robust and just use the case.  Do you want me to change it?

**Comment by dwhjames** [comment]
Oh… I haven’t actually tried it, but I assumed that the following would work:

```scala
wrapMethod[(GetObjectRequest, File), ObjectMetadata]((client.getObject _).tupled, getObjectRequest -> destinationFile)
```

A bit less syntax, but doesn’t really matter.

**Comment by marcinx27** [comment]
I dunno, man.  I think with the case, while it's a little syntax heavy, is a bit better in the sense of self-documentation.  I just think it's way clearer that the function being passed to wrapMethod is converting a tuple of `(getObjectRequest, destinationFile)` to the function of `getObject(GetObjectRequest, File)`.

All in all, this get object is a really weird case because it's one of the only functions in  the AWS S3 SDK that can't be reduced down to `f(X)` like `getObject(getObjectRequest: GetObjectRequest)`

**Comment by dwhjames** [comment]
Yeah, that’s fair—it does end up looking rather cryptic…

**Pull request merged**
